### ISSUE TITLE
modify `known_first_party` or custom sections for isort

### ISSUE THREAD

**Issue by danielknell** [Zac-HD/shed#45]
there is no way to set `known_first_party` or custom sections when using `shed`.

```toml
# pyproject.toml
[tool.isort]
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'TEST', 'FIRSTPARTY', 'LOCALFOLDER']
known_test = ["pytest"]
```

isort will work, but shed will then reorder the items back into third party.

same when isort needs help with first party modules.
